//--------------------------------------------------------------------
// <copyright file="StockIcon.cs" company="myapkapp">
//     Copyright (c) myapkapp. All rights reserved.
// </copyright>                                                                
//--------------------------------------------------------------------
// This open-source project is licensed under Apache License 2.0
//--------------------------------------------------------------------

namespace MyAPKapp.VistaUIFramework {
    public enum StockIcon {
        DocNoAssoc = 0,
        DocAssoc = 1,
        Application = 2,
        Folder = 3,
        FolderOpen = 4,
        Drive525 = 5,
        Drive35 = 6,
        DriveRemove = 7,
        DriveFixed = 8,
        DriveNet = 9,
        DriveNetDisabled = 10,
        DriveCD = 11,
        DriveRam = 12,
        World = 13,
        Server = 15,
        Printer = 16,
        MyNetwork = 17,
        Find = 22,
        Help = 23,
        Share = 28,
        Link = 29,
        SlowFile = 30,
        Recycler = 31,
        RecyclerFull = 32,
        MediaCDAudio = 40,
        Lock = 47,
        Autolist = 49,
        PrinterNet = 50,
        ServerShare = 51,
        PrinterFax = 52,
        PrinterFaxNet = 53,
        PrinterFile = 54,
        Stack = 55,
        MediaSVCD = 56,
        Stuffedfolder = 57,
        Driveunknown = 58,
        DriveDVD = 59,
        MediaDVD = 60,
        MediaDVDRAM = 61,
        MediaDVDRW = 62,
        MediaDVDR = 63,
        MediaDVDROM = 64,
        MediaCDAudioPlus = 65,
        MediaCDRW = 66,
        MediaCDR = 67,
        MediaCDburn = 68,
        MediaBlankCD = 69,
        MediaCDROM = 70,
        AudioFiles = 71,
        ImageFiles = 72,
        VideoFiles = 73,
        MixedFiles = 74,
        FolderBack = 75,
        FolderFront = 76,
        Shield = 77,
        Warning = 78,
        Info = 79,
        Error = 80,
        Key = 81,
        Software = 82,
        Rename = 83,
        Delete = 84,
        MediaAudioDVD = 85,
        MediaMovieDVD = 86,
        MediaEnhancedCD = 87,
        MediaEnhancedDVD = 88,
        MediaHDDVD = 89,
        MediaBluray = 90,
        MediaVCD = 91,
        MediaDVDPlusR = 92,
        MediaDVDPlusRW = 93,
        DesktopPC = 94,
        MobilePC = 95,
        Users = 96,
        MediaSmartMedia = 97,
        MediaCompactFlash = 98,
        DeviceCellphone = 99,
        DeviceCamera = 100,
        DeviceVideoCamera = 101,
        DeviceAudioPlayer = 102,
        NetworkConnect = 103,
        Internet = 104,
        Zipfile = 105,
        Settings = 106,
        DriveHDDVD = 132,
        DriveBD = 133,
        MediaHDDVDROM = 134,
        MediaHDDVDR = 135,
        MediaHDDVDRAM = 136,
        MediaBDROM = 137,
        MediaBDR = 138,
        MediaBDRE = 139,
        ClusteredDrive = 140
    }
}